### ISSUE TITLE
Module pyrabbit2

### ISSUE THREAD

**Issue by lunauser** [uhub/awesome-python#3]
Hi!

Try this module https://github.com/deslum/pyrabbit2. This is fork pyrabbit with new features and support

**Comment by ccding** [comment]
SPAM

**Comment by lunauser** [comment]
This is not spam. Try using

**Comment by ccding** [comment]
It is spam. Try knowing what this repo is

**Comment by ccding** [comment]
It is spam. Opening identical issues in 28 repos to advertise your project is definitely a spam. Try knowing what this repo is
